### ISSUE TITLE
app.py TypeError('port must be an integer') error

### ISSUE THREAD

**Issue by 0xlen** [abby-fuller/ecs-demo#3]
Hi Abby,

Thanks for your good tutorial for ecs demo.

When building the docker image for ecs-demo-web and ecs-demo-api:

```bash
$ cd <path/to/project>/ecs-demo/web
$ docker build -t ecs-demo-web .
$ cd <path/to/project>/ecs-demo/api 
$ docker build -t ecs-demo-api .
```

In the app.py, it specifies the string as the port number, this may occur the type error when running the docker image.

https://github.com/abby-fuller/ecs-demo/blob/ed773dfb1fd99796edb1ac003907cbd79d424961/web/app.py#L9

https://github.com/abby-fuller/ecs-demo/blob/ed773dfb1fd99796edb1ac003907cbd79d424961/api/app.py#L9

Error output
```python
Traceback (most recent call last):
  File "app.py", line 9, in <module>
    app.run(port='8000',host='0.0.0.0')
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 772, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 748, in run_simple
    raise TypeError('port must be an integer')
```

I open a PR to fix this issue and hope it helps.

**Comment by fbukevin** [comment]
Here are related flask official issue discussing about this case.

* app.run(port='5000', debug=True) error
https://github.com/pallets/flask/issues/2220

* Raise TypeError if port is not an integer
https://github.com/pallets/werkzeug/pull/1088



Change port type from string to integer works fine.
` app.run(port=3000,host='0.0.0.0') `
